
# This file is automatically generated, you probably don't want to edit this

jSumTTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jSumTTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            M1 = 0,
            SD1 = 0,
            n1 = 0,
            name1 = "One",
            M2 = 0,
            SD2 = 0,
            n2 = 0,
            name2 = "Two",
            hypo = "notequal",
            d_show = TRUE,
            CI_d_show = FALSE,
            CI_d_width = 95,
            Mdiff_show = TRUE,
            SEdiff_show = FALSE,
            CI_show = FALSE,
            CIdiff_width = 95,
            desc_show = TRUE,
            SE_M_show = TRUE,
            CI_M_show = TRUE,
            CI_M_width = 95,
            dplot_show = TRUE, ...) {

            super$initialize(
                package="jSumTTest",
                name="jSumTTest",
                requiresData=FALSE,
                ...)

            private$..M1 <- jmvcore::OptionNumber$new(
                "M1",
                M1,
                default=0)
            private$..SD1 <- jmvcore::OptionNumber$new(
                "SD1",
                SD1,
                default=0)
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1,
                default=0)
            private$..name1 <- jmvcore::OptionString$new(
                "name1",
                name1,
                default="One")
            private$..M2 <- jmvcore::OptionNumber$new(
                "M2",
                M2,
                default=0)
            private$..SD2 <- jmvcore::OptionNumber$new(
                "SD2",
                SD2,
                default=0)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2,
                default=0)
            private$..name2 <- jmvcore::OptionString$new(
                "name2",
                name2,
                default="Two")
            private$..hypo <- jmvcore::OptionList$new(
                "hypo",
                hypo,
                options=list(
                    "notequal",
                    "onegreater",
                    "twogreater"),
                default="notequal")
            private$..d_show <- jmvcore::OptionBool$new(
                "d_show",
                d_show,
                default=TRUE)
            private$..CI_d_show <- jmvcore::OptionBool$new(
                "CI_d_show",
                CI_d_show,
                default=FALSE)
            private$..CI_d_width <- jmvcore::OptionNumber$new(
                "CI_d_width",
                CI_d_width,
                min=50,
                max=99.9,
                default=95)
            private$..Mdiff_show <- jmvcore::OptionBool$new(
                "Mdiff_show",
                Mdiff_show,
                default=TRUE)
            private$..SEdiff_show <- jmvcore::OptionBool$new(
                "SEdiff_show",
                SEdiff_show,
                default=FALSE)
            private$..CI_show <- jmvcore::OptionBool$new(
                "CI_show",
                CI_show,
                default=FALSE)
            private$..CIdiff_width <- jmvcore::OptionNumber$new(
                "CIdiff_width",
                CIdiff_width,
                min=50,
                max=99.9,
                default=95)
            private$..desc_show <- jmvcore::OptionBool$new(
                "desc_show",
                desc_show,
                default=TRUE)
            private$..SE_M_show <- jmvcore::OptionBool$new(
                "SE_M_show",
                SE_M_show,
                default=TRUE)
            private$..CI_M_show <- jmvcore::OptionBool$new(
                "CI_M_show",
                CI_M_show,
                default=TRUE)
            private$..CI_M_width <- jmvcore::OptionNumber$new(
                "CI_M_width",
                CI_M_width,
                min=50,
                max=99.9,
                default=95)
            private$..dplot_show <- jmvcore::OptionBool$new(
                "dplot_show",
                dplot_show,
                default=TRUE)

            self$.addOption(private$..M1)
            self$.addOption(private$..SD1)
            self$.addOption(private$..n1)
            self$.addOption(private$..name1)
            self$.addOption(private$..M2)
            self$.addOption(private$..SD2)
            self$.addOption(private$..n2)
            self$.addOption(private$..name2)
            self$.addOption(private$..hypo)
            self$.addOption(private$..d_show)
            self$.addOption(private$..CI_d_show)
            self$.addOption(private$..CI_d_width)
            self$.addOption(private$..Mdiff_show)
            self$.addOption(private$..SEdiff_show)
            self$.addOption(private$..CI_show)
            self$.addOption(private$..CIdiff_width)
            self$.addOption(private$..desc_show)
            self$.addOption(private$..SE_M_show)
            self$.addOption(private$..CI_M_show)
            self$.addOption(private$..CI_M_width)
            self$.addOption(private$..dplot_show)
        }),
    active = list(
        M1 = function() private$..M1$value,
        SD1 = function() private$..SD1$value,
        n1 = function() private$..n1$value,
        name1 = function() private$..name1$value,
        M2 = function() private$..M2$value,
        SD2 = function() private$..SD2$value,
        n2 = function() private$..n2$value,
        name2 = function() private$..name2$value,
        hypo = function() private$..hypo$value,
        d_show = function() private$..d_show$value,
        CI_d_show = function() private$..CI_d_show$value,
        CI_d_width = function() private$..CI_d_width$value,
        Mdiff_show = function() private$..Mdiff_show$value,
        SEdiff_show = function() private$..SEdiff_show$value,
        CI_show = function() private$..CI_show$value,
        CIdiff_width = function() private$..CIdiff_width$value,
        desc_show = function() private$..desc_show$value,
        SE_M_show = function() private$..SE_M_show$value,
        CI_M_show = function() private$..CI_M_show$value,
        CI_M_width = function() private$..CI_M_width$value,
        dplot_show = function() private$..dplot_show$value),
    private = list(
        ..M1 = NA,
        ..SD1 = NA,
        ..n1 = NA,
        ..name1 = NA,
        ..M2 = NA,
        ..SD2 = NA,
        ..n2 = NA,
        ..name2 = NA,
        ..hypo = NA,
        ..d_show = NA,
        ..CI_d_show = NA,
        ..CI_d_width = NA,
        ..Mdiff_show = NA,
        ..SEdiff_show = NA,
        ..CI_show = NA,
        ..CIdiff_width = NA,
        ..desc_show = NA,
        ..SE_M_show = NA,
        ..CI_M_show = NA,
        ..CI_M_width = NA,
        ..dplot_show = NA)
)

jSumTTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jSumTTestResults",
    inherit = jmvcore::Group,
    active = list(
        ttesttable = function() private$.items[["ttesttable"]],
        desctable = function() private$.items[["desctable"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples Test for Summary Data")
            self$add(jmvcore::Table$new(
                options=options,
                name="ttesttable",
                title="Independent Samples Test for Summary Data",
                rows=2,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="d", 
                        `title`="Cohen&rsquo;s d", 
                        `type`="number", 
                        `visible`="(d_show)"),
                    list(
                        `name`="CI_d_low", 
                        `title`="Lower", 
                        `type`="number", 
                        `visible`="(d_show && CI_d_show)"),
                    list(
                        `name`="CI_d_upp", 
                        `title`="Upper", 
                        `type`="number", 
                        `visible`="(d_show && CI_d_show)"),
                    list(
                        `name`="Mdiff", 
                        `title`="&Delta;M", 
                        `type`="number", 
                        `visible`="(Mdiff_show)"),
                    list(
                        `name`="SEdiff", 
                        `title`="SE(&Delta;M)", 
                        `type`="number", 
                        `visible`="(Mdiff_show && SEdiff_show)"),
                    list(
                        `name`="CIlow", 
                        `title`="Lower", 
                        `type`="number", 
                        `visible`="(Mdiff_show && CI_show)"),
                    list(
                        `name`="CIupp", 
                        `title`="Upper", 
                        `type`="number", 
                        `visible`="(Mdiff_show && CI_show)")),
                notes=list(
                    `1`="INI"),
                refs=list(
                    "jSumTTest",
                    "psych-R")))
            self$add(jmvcore::Table$new(
                options=options,
                name="desctable",
                title="Group descriptives",
                visible="(desc_show)",
                rows=2,
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="M", 
                        `title`="M", 
                        `type`="number"),
                    list(
                        `name`="SD", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="SE(M)", 
                        `type`="number", 
                        `visible`="(desc_show && SE_M_show)"),
                    list(
                        `name`="CI_M_low", 
                        `title`="Lower", 
                        `superTitle`="Convidence Interval", 
                        `type`="number", 
                        `visible`="(desc_show && CI_M_show)"),
                    list(
                        `name`="CI_M_upp", 
                        `title`="Upper", 
                        `superTitle`="Convidence Interval", 
                        `type`="number", 
                        `visible`="(desc_show && CI_M_show)")),
                refs=list(
                    "jSumTTest")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Descriptives Plot (mean and 95 % CI)",
                width=400,
                height=300,
                renderFun=".plot",
                visible="(dplot_show)",
                refs=list(
                    "jSumTTest",
                    "ggplot2")))}))

jSumTTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jSumTTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jSumTTest",
                name = "jSumTTest",
                version = c(0,8,2),
                options = options,
                results = jSumTTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Independent Samples Test for Summary Data
#'
#' 
#' @param M1 .
#' @param SD1 .
#' @param n1 .
#' @param name1 .
#' @param M2 .
#' @param SD2 .
#' @param n2 .
#' @param name2 .
#' @param hypo .
#' @param d_show .
#' @param CI_d_show .
#' @param CI_d_width .
#' @param Mdiff_show .
#' @param SEdiff_show .
#' @param CI_show .
#' @param CIdiff_width .
#' @param desc_show .
#' @param SE_M_show .
#' @param CI_M_show .
#' @param CI_M_width .
#' @param dplot_show .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttesttable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desctable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttesttable$asDF}
#'
#' \code{as.data.frame(results$ttesttable)}
#'
#' @export
jSumTTest <- function(
    M1 = 0,
    SD1 = 0,
    n1 = 0,
    name1 = "One",
    M2 = 0,
    SD2 = 0,
    n2 = 0,
    name2 = "Two",
    hypo = "notequal",
    d_show = TRUE,
    CI_d_show = FALSE,
    CI_d_width = 95,
    Mdiff_show = TRUE,
    SEdiff_show = FALSE,
    CI_show = FALSE,
    CIdiff_width = 95,
    desc_show = TRUE,
    SE_M_show = TRUE,
    CI_M_show = TRUE,
    CI_M_width = 95,
    dplot_show = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jSumTTest requires jmvcore to be installed (restart may be required)")


    options <- jSumTTestOptions$new(
        M1 = M1,
        SD1 = SD1,
        n1 = n1,
        name1 = name1,
        M2 = M2,
        SD2 = SD2,
        n2 = n2,
        name2 = name2,
        hypo = hypo,
        d_show = d_show,
        CI_d_show = CI_d_show,
        CI_d_width = CI_d_width,
        Mdiff_show = Mdiff_show,
        SEdiff_show = SEdiff_show,
        CI_show = CI_show,
        CIdiff_width = CIdiff_width,
        desc_show = desc_show,
        SE_M_show = SE_M_show,
        CI_M_show = CI_M_show,
        CI_M_width = CI_M_width,
        dplot_show = dplot_show)

    analysis <- jSumTTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

